name: flutterapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.6
  dio: ^2.0.5
  fluro: "^1.4.0"
  flutter_swiper: "^1.1.4"
  event_bus: "^1.0.3"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
   - images/icon/phone_icon.png
   - images/icon/pas_icon.png
   - images/icon/backBtn_1.png
   - images/icon/phone_icon_1.png
   - images/icon/verificationCode.png
   - images/icon/verificationCode_1.png
   - images/icon/pas_icon_1.png
   - images/icon/ishide_1.png
   - images/icon/ishide_2.png
   - images/icon/isopen_1.png
   - images/icon/isopen_2.png
   - images/icon/serch.png
   - images/icon/home_1.png
   - images/icon/shopping_1.png
   - images/icon/mine_1.png
   - images/icon/home.png
   - images/icon/shopping.png
   - images/icon/mine.png
   - images/icon/TOP.png
   - images/icon/isactive.png
   - images/icon/noactive.png
   - images/icon/decrease.png
   - images/icon/increase.png
   - images/icon/star.png
   - images/icon/setting.png
   - images/icon/right_icon.png
   - images/icon/complete.png
   - images/icon/delivery.png
   - images/icon/receiving.png
   - images/icon/obligation.png
   - images/icon/rule.png
   - images/icon/fans.png
   - images/icon/order.png
   - images/icon/back.png
   - images/icon/share.png
   - images/icon/addShopping.png
   - images/icon/nowBuy.png
   - images/icon/pinkage.png
   - images/icon/goBrand.png
   - images/icon/ensureBtn.png
   - images/icon/position.png
   - images/icon/default.png
   - images/icon/self.png
   - images/icon/self_1.png
   - images/icon/fansbtn.png
   - images/icon/fansbtn_1.png
   - images/icon/questions.png
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
